// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxafbzF8l6VJUnbutMehstM3fH-10jUSQ',
    appId: '1:383740665458:web:417ed9c255cda53ed22ceb',
    messagingSenderId: '383740665458',
    projectId: 'lakbay-app-166bf',
    authDomain: 'lakbay-app-166bf.firebaseapp.com',
    storageBucket: 'lakbay-app-166bf.firebasestorage.app',
    measurementId: 'G-V11KW9LTD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDShtFIfx7JX4NgXCZOXSzYyMLjq9MKVd4',
    appId: '1:383740665458:android:fd313db546a49047d22ceb',
    messagingSenderId: '383740665458',
    projectId: 'lakbay-app-166bf',
    storageBucket: 'lakbay-app-166bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Mx2s9Pb51LTwD7MEq7z7zFJlP6rBhXw',
    appId: '1:383740665458:ios:8c21c630d1a9a966d22ceb',
    messagingSenderId: '383740665458',
    projectId: 'lakbay-app-166bf',
    storageBucket: 'lakbay-app-166bf.firebasestorage.app',
    iosBundleId: 'com.example.lakbayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Mx2s9Pb51LTwD7MEq7z7zFJlP6rBhXw',
    appId: '1:383740665458:ios:8c21c630d1a9a966d22ceb',
    messagingSenderId: '383740665458',
    projectId: 'lakbay-app-166bf',
    storageBucket: 'lakbay-app-166bf.firebasestorage.app',
    iosBundleId: 'com.example.lakbayApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxafbzF8l6VJUnbutMehstM3fH-10jUSQ',
    appId: '1:383740665458:web:e14513efd0db9b78d22ceb',
    messagingSenderId: '383740665458',
    projectId: 'lakbay-app-166bf',
    authDomain: 'lakbay-app-166bf.firebaseapp.com',
    storageBucket: 'lakbay-app-166bf.firebasestorage.app',
    measurementId: 'G-P7RJPWZB9X',
  );

}